name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build for Web
        if: matrix.os == 'ubuntu-latest'
        run: flutter build web

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: flutter build windows

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter build linux

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/web/**/*
            build/windows/runner/Release/*.exe
            build/linux/x64/release/bundle/*
        env:
          GITHUB_TOKEN: ${{ secrets.GHP }}
